### ISSUE TITLE
train_miss.py代码好像有点问题，用测试集来选取最佳模型了

### ISSUE THREAD

**Issue by Norwa9** [AIM3-RUC/MMIN#10]
运行CAP_MMIN.sh时，第143行tst_dataset的acc,uar把137行val_dataset的acc,uar给覆盖了，所以实际上每个训练epoch记录的是测试集上最好的效果。。

https://github.com/AIM3-RUC/MMIN/blob/f75331b17f0130b821c9587aca7a5704d72caab6/train_miss.py#L136-L155

重新跑了一遍以后result_total.csv记录的结果如下：
acc	uar	f1
0.6010	0.6256	0.5926
0.6197	0.6551	0.6247
0.6542	0.6589	0.6573
0.6212	0.6604	0.6259
0.6060	0.5980	0.5992
0.5983	0.6048	0.6024
0.6544	0.6376	0.6166
0.6342	0.6311	0.6135
0.6545	0.6615	0.6506
0.5952	0.6127	0.5926
0.6239	0.6346	0.6175

**Comment by zxpoqas123** [comment]
Thanks for your notification!
I found that this problem exists in both the train_baseline.py and train_miss.py.
And this problem will be triggered when the arguments --verbose is set to TRUE.
For a fair comparison, I suggest setting --verbose to FALSE in all the *.sh scripts?

**Comment by cyang810** [comment]
为什么我跑的这么高？
acc	uar	f1
0.7102	0.7341	0.6901
0.7576	0.8009	0.7642
0.7879	0.8033	0.7929
0.7399	0.7926	0.7537
0.7529	0.7540	0.7582
0.7488	0.7524	0.7535
0.8125	0.7847	0.7827
0.8220	0.7879	0.7914
0.7881	0.8162	0.7947
0.7527	0.7496	0.7442
0.7673	0.7776	0.7626

**Comment by htqh06** [comment]
您好，请问你知道'azz', 'zvz', 'zzl', 'avz', 'azl', 'zvl'这些缩写是代表的什么吗
